### ISSUE TITLE
Interface with OKCupid broken

### ISSUE THREAD

**Issue by bitromantic** [IvanMalison/okcupyd#34]
It appears changes at OKCupid have created problems with okcupyd interface with OKCupid. Attempts to search generate out-of-range errors. Here is the call tree when trying to run a test implementation of my okc automation script.

```
Traceback (most recent call last):
  File "okctest.py", line 112, in <module>
    main()
  File "okctest.py", line 109, in main
    process_task(task, profiles)
  File "okctest.py", line 5, in process_task
    for profile in profiles[:200]:
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/util/fetchable.py", line 192, in __getitem__
    return self._handle_slice(item)
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/util/fetchable.py", line 218, in _handle_slice
    value = next(iterator)
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/util/fetchable.py", line 164, in _make_nice_repr_iterator
    for item in original_iterable:
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/util/fetchable.py", line 284, in fetch
    for item in self._processor.process(text_response):
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/util/fetchable.py", line 315, in process
    yield self._object_factory(element)
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/search.py", line 232, in <lambda>
    **MatchCardExtractor(match_card_div).as_dict
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/search.py", line 198, in as_dict
    'id': self.id,
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/search.py", line 151, in id
    return int(self._id_xpb.one_(self._div))
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/xpath.py", line 75, in one_
    return self.apply_(tree)[0]
IndexError: list index out of range
```

The change at OKCupid must have happened within the last two weeks, as the full automation script and this test worked fine not too long ago.

**Comment by sagittarian** [comment]
I was also getting this last week, but just now all the profiles I had tried to access that the script barfed on with this error seem to be working fine, so it seems that okcupid reverted whatever change they had made.

**Comment by IvanMalison** [comment]
@sagittarian Were you using search? I think that this should only happen when you are searching.

The relevant piece of code is:
``` python
_id_xpb = xpb.button.with_classes(
        "match_card_rating",
        "binary_rating_button"
).select_attribute_('data-tuid')
```

So i guess the spot in the dom to look for is the new binary rating button. Maybe there are some cases where this attribute is on the button and others where it isn't?

**Comment by sagittarian** [comment]
Nevermind, the error I was getting was different.  It just involved the same line in xpath.py.

I have been running searches this evening however and haven't had a problem.

**Comment by IvanMalison** [comment]
yeah, that line in xpath will almost always be the last line in any traceback that results from a change in the structure of the okc DOM, so it really could be just about anything.

Do you have a traceback of the error you were getting? it is probably also an issue worth looking in to.

**Comment by sagittarian** [comment]
The relevant part is here:
```
  File "/home/amesha/src/okcupyd/okcupyd/util/__init__.py", line 49, in __get__
    value = self.func(obj)
  File "/home/amesha/src/okcupyd/okcupyd/profile.py", line 203, in id
    return int(self._id_xpb.one_(self.profile_tree))
  File "/home/amesha/src/okcupyd/okcupyd/xpath.py", line 75, in one_
    return self.apply_(tree)[0]
IndexError: list index out of range
```
It was caused by an attempt to access profile.id.  As I said everything is working now however with no changes.

**Comment by IvanMalison** [comment]
huh okay, let me know if you see it again. It could be something that only happens on certain profiles, so the target username would also be helpful

**Comment by sagittarian** [comment]
I went back and accessed the same profiles in the same way and didn't get the problem, so it's really gone for now.  If I see it again and I'll you know.

**Comment by IvanMalison** [comment]
@sagittarian Did you say that search is working for you? I am getting the error that @bitromantic reported on my accounts.

**Comment by IvanMalison** [comment]
@bitromantic This should now be fixed. Can you confirm?

**Comment by sagittarian** [comment]
The problem I was getting (with profile.id) seems to have been related to a network issue on my end, nothing to do with changes at okcupid.  The reason that search was working for me was that I had fixed the code when my searches broke and forgot about it.

**Comment by IvanMalison** [comment]
> The problem I was getting (with profile.id) seems to have been related to a network issue on my end, nothing to do with changes at okcupid. The reason that search was working for me was that I had fixed the code when my searches broke and forgot about it.

Cool. Definitely let me know if you have any other fixes that are lying around.

I'm thinking about trying to set up travis to run against the live site every so often, so I can find out when things break, but for now I only learn about breakages from the relatively small group of okcupyd users, since I havent been using okcupyd very actively as of late (since my ip has been banned and my account has been deleted).
