### ISSUE TITLE
how to search for those who you have not contacted?

### ISSUE THREAD

**Issue by markyann11** [IvanMalison/okcupyd#49]
I see this part of the code in search.py but I dont know how to use it so I can only message people I have not messaged before.
    def contacted(self):
        return bool(xpb.div.with_class('fancydate').apply_(self._div))

**Comment by IvanMalison** [comment]
I don't believe that it is possible to make search only return people that you haven't contacted, but it should be easy to perform some action only on those you havent contacted: as follows:

``` python
for profile in user.search():
   if not profile.contacted:
      profile.message("Hey")
```

**Comment by markyann11** [comment]
@IvanMalison awesome thanks !
