### ISSUE TITLE
how to flush the messages to a database ?

### ISSUE THREAD

**Issue by markyann11** [IvanMalison/okcupyd#50]
when it hits the 300 messages, how can I move all the messages to a database (so I don't loose track of converastions) and clean the okcupid inbox?

**Comment by IvanMalison** [comment]
There is a db module in the okcupyd library that should help with this.

basically:

``` python
from okcupyd.db import mailbox
from okcupyd.user import User
user = User()
mailbox.Sync(user).all()
```

You will need to delete the messages separately.
