### ISSUE TITLE
how can I run the script out of shell?

### ISSUE THREAD

**Issue by markyann11** [IvanMalison/okcupyd#51]

**Comment by IvanMalison** [comment]
What do you mean? Like how can you use it in your own python program?

**Comment by markyann11** [comment]
for example let say I have a collection of commands that I type into the okcupyd shell ( I enter them manually)

I wanna put all of them in a shell script or python script, and just run them with one command ( I dont wanna copy paste my scripts to the shell) how can I do that ?
