### ISSUE TITLE
how to sort search result by distance or other things (last time online)?

### ISSUE THREAD

**Issue by markyann11** [IvanMalison/okcupyd#52]

**Comment by IvanMalison** [comment]
Have you checked out http://okcupyd.readthedocs.org/en/latest/ ?

see http://okcupyd.readthedocs.org/en/latest/public.html#searchfetchable for details about the arguments that you can pass to search to filter

A lot of these questions that you are asking are answered in the okcupyd docs. github issues aren't really the best way to ask questions like this. If you have specific questions that aren't answered in http://okcupyd.readthedocs.org/en/latest/ you can shoot me an email at (my username)@gmail.com
