### ISSUE TITLE
How does the distance/location filter work?

### ISSUE THREAD

**Issue by chrism2671** [IvanMalison/okcupyd#54]
I'm trying to build a search with e.g. distance = 100km of location = London, UK, just like on the website.

I can see the location parameter is an integer, so I'm guessing this is a distance. If so, where does the location string go, or is it some kind of location ID from OKC?

This is my current search.

    results = u.search(age_min=25, age_max=33,order_by='match', height_max=78)

**Comment by IvanMalison** [comment]
http://okcupyd.readthedocs.org/en/latest/public.html#searchfetchable .
location – A location string which will be used to filter results.
radius (int) – The maximum distance from the specified location of returned search results.

**Comment by chrism2671** [comment]
Super, thank you!
