### ISSUE TITLE
Doesnt work anymore since okcupid changed UI

### ISSUE THREAD

**Issue by markyann11** [IvanMalison/okcupyd#55]

**Comment by IvanMalison** [comment]
Everything? When did this happen?

**Comment by markyann11** [comment]
Somethings work, like deleting messages from inbox, but messaging people doesns't work.
Okcupid recently changed their user interface completely .

**Comment by IvanMalison** [comment]
:( I was afraid something like that might happen. I'll look in to it and see how hard it will be to get things working again.

**Comment by IvanMalison** [comment]
Hmmm. A lot of things still work for me. Can you help me a compile a list of things that aren't working?

**Comment by IvanMalison** [comment]
I was able to reply to a message as well. How are you sending a message?

**Comment by IvanMalison** [comment]
@markyann11 Things seem to be working for me. Can you clarify what your issues are? Can i close this issue?
