### ISSUE TITLE
Ability to change your answers

### ISSUE THREAD

**Issue by Euphorbium** [IvanMalison/okcupyd#56]
Perhaps it is there, but I did not find it. It would be a nice feature to have.

**Comment by Euphorbium** [comment]
Found it, it is Questions.respond method.

**Comment by IvanMalison** [comment]
Yeah. Responding to a question is actually somewhat complicated. You probably want `respond_from_user_question` or `respond_from_question`. There is no method on Question on UserQuestion because those objects don't have session instances.
