### ISSUE TITLE
user.inbox.messages gives short output

### ISSUE THREAD

**Issue by claydegruchy** [IvanMalison/okcupyd#65]
Real simple in:

user = okcupyd.User()

first_thread = user.inbox[0]
print(first_thread.messages.id)

It seems to only put out something like:

<Fetchable[Message][<Message: Senderman sent Otherperson "I have ter...">, ...]>

Is this a limitation or am I missing something?

Cheers friend.

**Comment by IvanMalison** [comment]
read the docstring for fetchable

**Comment by IvanMalison** [comment]
also things might be broken right now

**Comment by IvanMalison** [comment]
Were you able to figure this out:
http://okcupyd.readthedocs.org/en/latest/okcupyd.util.html?highlight=fetchable#module-okcupyd.util.fetchable

Let me know if i can close

**Comment by claydegruchy** [comment]
Hey, I didnt end up sorting this out but only I started python a week ago
so don't stress about what I think.

On 4 August 2015 at 08:14, IvanMalison <notifications@github.com> wrote:

> Were you able to figure this out:
>
> http://okcupyd.readthedocs.org/en/latest/okcupyd.util.html?highlight=fetchable#module-okcupyd.util.fetchable
>
> Let me know if i can close
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IvanMalison/okcupyd/issues/65#issuecomment-127504830>.
>



-- 
Clay DeGruchy.

**Comment by claydegruchy** [comment]
Scratch that, I just looked into it again then. seems I wasnt putting the
right elements in.

I was using
okcupyd.user.User(session).inbox[0]

which was only returning the title of the inbox. but what i really needed
was

okcupyd.user.User(session).inbox[0].messages[0].*content*

which returns the full message.

thanks for your help.

On 4 August 2015 at 09:18, GeDruchy . <clay.degruchy@gmail.com> wrote:

> Hey, I didnt end up sorting this out but only I started python a week ago
> so don't stress about what I think.
>
> On 4 August 2015 at 08:14, IvanMalison <notifications@github.com> wrote:
>
>> Were you able to figure this out:
>>
>> http://okcupyd.readthedocs.org/en/latest/okcupyd.util.html?highlight=fetchable#module-okcupyd.util.fetchable
>>
>> Let me know if i can close
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/IvanMalison/okcupyd/issues/65#issuecomment-127504830>
>> .
>>
>
>
>
> --
> Clay DeGruchy.
>



-- 
Clay DeGruchy.

**Comment by IvanMalison** [comment]
Cool, glad I could help.
