### ISSUE TITLE
function okc_post() is not defined in the repository

### ISSUE THREAD

**Issue by CrazySyntax** [IvanMalison/okcupyd#89]
Hi, 
I saw that the code uses several times the function okc_post. I searched for this function name repository, and I didn't find this function definition (something like def okc_post(...)). Can you show me this function?

**Comment by colonelpanic8** [comment]
Yeah thats because its defined through meta programming

https://github.com/IvanMalison/okcupyd/blob/46f4eaa9419098f6c299738ce148af55c64deb64/okcupyd/session.py#L139
